FROM fedora:40

RUN dnf update -y

RUN dnf install -y python3-pip python3-flask python3-pillow python3-requests python3-numpy python3-scikit-learn python3-waitress

RUN pip3 install faiss-cpu
RUN pip3 install datasets
RUN pip3 install transformers
RUN pip3 install torchvision


WORKDIR /app

COPY . .

RUN ls -la

ENTRYPOINT [ "python3", "main.py" ]